---
# defaults file for upgrade
log_directory: /var/log/ripu
log_file: "{{ log_directory }}/ripu.log"

# leapp_upgrade_type: connected
leapp_upgrade_type: disconnected

leapp_upgrade_opts: "{{ '--no-rhsm' if leapp_upgrade_type == 'connected' else '' }}"

result_filename: '/var/log/leapp/leapp-report.txt'
...
