---
# handlers file for logging
- name: Archive log file
  ansible.builtin.shell: |
    echo Job ended at $(date -Is) >> {{ log_file }}
    mv {{ log_file }} {{ log_file }}-{{ ansible_date_time.iso8601_basic_short }}
...
