---
# tasks file for upgrade
# TODO: Include tasks for RHEL 6 to 7 non-leapp upgrade
# - name: Include tasks for upgrade using redhat-upgrade-tool
#   ansible.builtin.include_tasks: upgrade-redhat-upgrade-tool.yml
#   when: ansible_distribution_major_version|int < 7

- name: Include tasks for leapp upgrade
  ansible.builtin.include_tasks: upgrade-leapp.yml
  when: ansible_distribution_major_version|int >= 7
...
