---
- name: Filesystem capacity checks
  ansible.builtin.script: check-inodes.sh
  changed_when: false
  when: bypass_fs_checks is not defined or (bypass_fs_checks is defined and bypass_fs_checks | lower != 'yes')

- name: Install packages for preupgrade analysis
  ansible.builtin.yum:
    name: "{{ analysis_packages_el7 }}"
    enablerepo: "{{ analysis_repos_el7 }}"
    state: latest

- name: Leapp preupgrade report
  ansible.builtin.shell: |
    set -o pipefail
    leapp preupgrade {{ leapp_preupg_opts }} 2>&1 | tee -a {{ log_file }}
  async: 43200
  poll: 60
  register: leapp
  args:
    executable: /bin/bash
  ignore_errors: true

- name: Result file status
  ansible.builtin.stat:
    path: "{{ result_filename }}"
  register: result

- name: Check that result file exists
  ansible.builtin.assert:
    that: result.stat.exists
    msg: "The preupgrade analysis report file {{ result_filename }} was not created."

- name: Preupgrade analysis report is done
  ansible.builtin.debug:
    msg: "The preupgrade analysis report generation is now complete. Review the result file at {{ result_filename }}."
...
