---
- name: Ensure leapp metadata is available for disconnected Leapp upgrades
  when: leapp_upgrade_type == 'disconnected'
  block:
    - name: /etc/leapp/files directory exists
      ansible.builtin.file:
        path: /etc/leapp/files
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Leapp utility metadata is installed
      ansible.builtin.unarchive:
        src: "{{ leapp_metadata_url }}"
        dest: /etc/leapp/files
        remote_src: true
        owner: root
        group: root

- name: Filesystem capacity checks
  ansible.builtin.script: check-inodes.sh
  changed_when: false
  when: bypass_fs_checks is not defined or (bypass_fs_checks is defined and bypass_fs_checks | lower != 'yes')

- name: Install packages for preupgrade analysis on RHEL 7
  ansible.builtin.yum:
    name: "{{ analysis_packages_el7 }}"
    enablerepo: "{{ analysis_repos_el7 }}"
    state: latest
  when: ansible_distribution_major_version|int == 7

- name: Install packages for preupgrade analysis on RHEL 8
  ansible.builtin.yum:
    name: "{{ analysis_packages_el8 }}"
    state: latest
  when: ansible_distribution_major_version|int == 8

- name: Leapp preupgrade report
  ansible.builtin.shell: |
    set -o pipefail
    leapp preupgrade {{ leapp_preupg_opts }} 2>&1 | tee -a {{ log_file }}
  async: 43200
  poll: 60
  register: leapp
  args:
    executable: /bin/bash
  ignore_errors: true

- name: Result file status
  ansible.builtin.stat:
    path: "{{ result_filename }}"
  register: result

- name: Check that result file exists
  ansible.builtin.assert:
    that: result.stat.exists
    msg: "The preupgrade analysis report file {{ result_filename }} was not created."

- name: Preupgrade analysis report is done
  ansible.builtin.debug:
    msg: "The preupgrade analysis report generation is now complete. Review the result file at {{ result_filename }}."
...
