---
# tasks file for analysis
# TODO: Include tasks for RHEL 6 to 7 non-leapp upgrade
# - name: Include tasks for preupg assistant analysis
#   ansible.builtin.include_tasks: analysis-preupg.yml
#   when: ansible_distribution_major_version|int < 7

- name: Include tasks for leapp preupgrade analysis
  ansible.builtin.include_tasks: analysis-leapp.yml
  when: ansible_distribution_major_version|int >= 7
...
