---
- name: Upgrade
  hosts: all
  strategy: free
  become: true
  tasks:
    - name: Initialize lock and logging
      ansible.builtin.import_role:
        name: logging
      vars:
        job_name: 'RIPU in-place OS upgrade'

    - name: Perform OS upgrade
      block:
        - name: Leapp upgrade
          ansible.builtin.import_role:
            name: upgrade
...
